#!/bin/bash

~/scripts/autostart &

# Only run sxhkd if it isn't already
if ! pgrep sxhkd; then
    sxhkd &
fi

bspc monitor -d web chat games term misc misc2

bspc config focused_border_color    "#8002f5"
bspc config focus_follows_pointer   true
bspc config automatic_scheme        alternate
bspc config initial_polarity        second_child
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc config pointer_modifier        mod4
bspc config pointer_action3         none
bspc config click_to_focus          none

bspc config top_padding             22
bspc config bottom_padding          0
bspc config left_padding            0
bspc config right_padding           0
bspc config border_width            1
bspc config window_gap              6
bspc config split_ratio             0.52

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
