#!/bin/sh

# Only run the program if it isn't already.
run() {
    if ! pgrep "$1" ; then
        "$@" &
    fi
}

run ~/.fehbg &
run ~/.config/polybar/launch.sh &
run discord &
# On NixOS Discord is capitalized
run Discord &
run gammy &
run flameshot &
run nm-applet &
